project_id = "tgzyttzmtsnlxxiywoww"

[functions.guru-chat]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.leetcode-daily]
verify_jwt = false

[functions.leetcode-snippets]
verify_jwt = false

[functions.leetcode-problem]
verify_jwt = false

[functions.leetcode-user]
verify_jwt = false