import type { PublicCodingProblem } from "@/lib/contest/types";

/**
 * Initial Java interview problem bank for the coding contest.
 *
 * PUBLIC DATA ONLY. This file is bundled into the browser, so it must never
 * contain `hiddenTestCases` or a `referenceSolution`. The authoritative
 * versions of those live in
 * `supabase/migrations/*_add_coding_contest.sql` (seeded into `coding_problems`,
 * a table with no client SELECT policy) and are read only by the
 * `contest-coding` edge function.
 *
 * Every problem is rendered generically from this model — there is no
 * problem-specific UI logic anywhere in the workspace.
 *
 * Input convention: every problem reads newline-separated plain text, which is
 * what the server-side runner feeds it. The `Main` driver is generated by the
 * existing `@/lib/javaHarness` helpers against `functionSignature` and appended
 * to `starterCode` at execution time, so `starterCode` stays a clean `Solution`
 * class for the learner.
 */

export const PUBLIC_JAVA_PROBLEMS: PublicCodingProblem[] = [
  {
    id: "java:two-sum-indices",
    slug: "two-sum-indices",
    title: "Return the indices of the pair that sums to the target",
    description:
      "Given an array of integers and a target, return the 0-based indices of the two values that add up to the target. Return them in ascending order. Each input has exactly one solution, and you may not reuse the same element twice.",
    difficulty: "easy",
    topics: ["Arrays", "HashMap"],
    constraints: [
      "2 <= nums.length <= 10^4",
      "-10^9 <= nums[i] <= 10^9",
      "Exactly one valid answer exists",
    ],
    inputFormat:
      "Line 1: n\nLine 2: n space-separated integers\nLine 3: target",
    outputFormat: "Two space-separated 0-based indices, smaller index first.",
    examples: [
      {
        input: "4\n2 7 11 15\n9",
        output: "0 1",
        explanation: "nums[0] + nums[1] === 2 + 7 === 9.",
      },
      {
        input: "2\n3 2 4\n6",
        output: "1 2",
        explanation: "2 + 4 === 6, at indices 1 and 2.",
      },
    ],
    starterCode: `import java.util.HashMap;
import java.util.Map;

class Solution {
    public int[] twoSum(int[] nums, int target) {
        // Your solution here.
        return new int[0];
    }
}
`,
    functionSignature: "public int[] twoSum(int[] nums, int target)",
    visibleTestCases: [
      { id: "visible-1", input: "4\n2 7 11 15\n9", expectedOutput: "0 1" },
      { id: "visible-2", input: "2\n3 2 4\n6", expectedOutput: "1 2" },
      { id: "visible-3", input: "5\n1 5 9 2 8\n10", expectedOutput: "2 3" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:maximum-subarray-sum",
    slug: "maximum-subarray-sum",
    title: "Maximum sum of a contiguous subarray",
    description:
      "Given an integer array, return the largest sum obtainable from any contiguous, non-empty subarray.",
    difficulty: "medium",
    topics: ["Arrays", "Dynamic Programming"],
    constraints: [
      "1 <= nums.length <= 100_000",
      "-10^4 <= nums[i] <= 10^4",
    ],
    inputFormat: "Line 1: n\nLine 2: n space-separated integers",
    outputFormat: "A single integer: the maximum subarray sum.",
    examples: [
      {
        input: "9\n-2 1 -3 4 -1 2 1 -5 4",
        output: "6",
        explanation: "The subarray [4, -1, 2, 1] sums to 6.",
      },
      {
        input: "1\n-5",
        output: "-5",
        explanation: "A single negative element is the best non-empty choice.",
      },
    ],
    starterCode: `class Solution {
    public int maxSubArray(int[] nums) {
        // Your solution here.
        return 0;
    }
}
`,
    functionSignature: "public int maxSubArray(int[] nums)",
    visibleTestCases: [
      {
        id: "visible-1",
        input: "9\n-2 1 -3 4 -1 2 1 -5 4",
        expectedOutput: "6",
      },
      { id: "visible-2", input: "1\n-5", expectedOutput: "-5" },
      { id: "visible-3", input: "5\n1 2 3 4 5", expectedOutput: "15" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:merge-intervals",
    slug: "merge-intervals",
    title: "Merge overlapping intervals",
    description:
      "Given closed intervals [start, end], merge every pair of overlapping intervals and return the non-overlapping intervals that cover all of the input.",
    difficulty: "medium",
    topics: ["Sorting & Searching", "Collections"],
    constraints: [
      "1 <= intervals.length <= 10^4",
      "0 <= start <= end <= 10^4",
      "Intervals are not given in sorted order",
    ],
    inputFormat:
      "Line 1: m (number of intervals)\nThen m lines, each: start end",
    outputFormat:
      "One line per merged interval: start end, ordered by start.",
    examples: [
      {
        input: "5\n1 3\n2 6\n8 10\n15 18\n8 9",
        output: "1 6\n8 10\n15 18",
        explanation: "[1,3] and [2,6] overlap; [8,10] and [8,9] overlap.",
      },
      {
        input: "1\n4 7",
        output: "4 7",
        explanation: "A single interval is already merged.",
      },
    ],
    starterCode: `import java.util.ArrayList;
import java.util.List;

class Solution {
    public List<List<Integer>> merge(List<List<Integer>> intervals) {
        // Your solution here.
        return new ArrayList<>();
    }
}
`,
    functionSignature:
      "public List<List<Integer>> merge(List<List<Integer>> intervals)",
    visibleTestCases: [
      {
        id: "visible-1",
        input: "5\n1 3\n2 6\n8 10\n15 18\n8 9",
        expectedOutput: "1 6\n8 10\n15 18",
      },
      { id: "visible-2", input: "1\n4 7", expectedOutput: "4 7" },
      {
        id: "visible-3",
        input: "3\n1 4\n4 5\n2 3",
        expectedOutput: "1 5",
      },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:first-position-of-target",
    slug: "first-position-of-target",
    title: "First position of a target in a sorted array (recursive)",
    description:
      "The array is sorted in ascending order. Using recursion rather than the standard library search, return the index of the first occurrence of target, or -1 when it is absent. When duplicates exist, the first occurrence must be returned.",
    difficulty: "easy",
    topics: ["Sorting & Searching", "Recursion"],
    constraints: [
      "0 <= nums.length <= 10^5",
      "nums is sorted in non-decreasing order",
    ],
    inputFormat:
      "Line 1: n\nLine 2: n space-separated integers (may be empty for n = 0)\nLine 3: target",
    outputFormat: "A single integer: the first index of target, or -1.",
    examples: [
      {
        input: "7\n1 2 2 2 3 4 5\n2",
        output: "2",
        explanation: "2 first appears at index 2, not at 1 or 3.",
      },
      {
        input: "4\n1 3 5 7\n4",
        output: "-1",
        explanation: "4 is not present.",
      },
    ],
    starterCode: `class Solution {
    public int search(int[] nums, int target) {
        // Your solution here (use a private recursive helper if you like).
        return -1;
    }
}
`,
    functionSignature: "public int search(int[] nums, int target)",
    visibleTestCases: [
      { id: "visible-1", input: "7\n1 2 2 2 3 4 5\n2", expectedOutput: "2" },
      { id: "visible-2", input: "4\n1 3 5 7\n4", expectedOutput: "-1" },
      { id: "visible-3", input: "0\n\n9", expectedOutput: "-1" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:group-anagrams",
    slug: "group-anagrams",
    title: "Group anagrams together",
    description:
      "Given an array of strings, group the anagrams together and return the groups. The relative order of the groups follows the first appearance of any member.",
    difficulty: "medium",
    topics: ["HashMap", "Strings", "Sorting & Searching"],
    constraints: [
      "1 <= strs.length <= 10^4",
      "0 <= strs[i].length <= 100",
      "strs[i] contains lowercase English letters only",
    ],
    inputFormat:
      "Line 1: k (number of strings)\nThen k lines, one string per line",
    outputFormat:
      "One group per line; members separated by a single space.",
    examples: [
      {
        input: "6\neat\ntea\ntan\nate\nnat\nbat",
        output: "eat tea ate\ntan nat\nbat",
        explanation: "eat/tea/ate share a key; tan/nat share one; bat is alone.",
      },
      {
        input: "1\na",
        output: "a",
        explanation: "A single string forms its own group.",
      },
    ],
    starterCode: `import java.util.ArrayList;
import java.util.List;

class Solution {
    public List<List<String>> groupAnagrams(List<String> strs) {
        // Your solution here.
        return new ArrayList<>();
    }
}
`,
    functionSignature: "public List<List<String>> groupAnagrams(List<String> strs)",
    visibleTestCases: [
      {
        id: "visible-1",
        input: "6\neat\ntea\ntan\nate\nnat\nbat",
        expectedOutput: "eat tea ate\ntan nat\nbat",
      },
      { id: "visible-2", input: "1\na", expectedOutput: "a" },
      {
        id: "visible-3",
        input: "3\nab\nba\nabc",
        expectedOutput: "ab ba\nabc",
      },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:longest-substring-without-repeating",
    slug: "longest-substring-without-repeating",
    title: "Longest substring without repeating characters",
    description:
      "Return the length of the longest contiguous substring that contains no repeated character.",
    difficulty: "medium",
    topics: ["Strings", "Collections"],
    constraints: [
      "0 <= s.length <= 10^5",
      "s contains printable ASCII characters only",
    ],
    inputFormat: "Line 1: the string s (may be empty)",
    outputFormat: "A single integer: the length of the longest such substring.",
    examples: [
      {
        input: "abcabcbb",
        output: "3",
        explanation: '"abc" repeats nowhere; the answer is 3.',
      },
      {
        input: "bbbbb",
        output: "1",
        explanation: "Only a single character can be kept.",
      },
    ],
    starterCode: `class Solution {
    public int lengthOfLongestSubstring(String s) {
        // Your solution here.
        return 0;
    }
}
`,
    functionSignature: "public int lengthOfLongestSubstring(String s)",
    visibleTestCases: [
      { id: "visible-1", input: "abcabcbb", expectedOutput: "3" },
      { id: "visible-2", input: "bbbbb", expectedOutput: "1" },
      { id: "visible-3", input: "pwwkew", expectedOutput: "3" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:valid-parentheses",
    slug: "valid-parentheses",
    title: "Valid parentheses",
    description:
      "Given a string containing only the characters ( ) [ ] {, decide whether the brackets are balanced: every opening bracket is closed by the same type of bracket in the correct order.",
    difficulty: "easy",
    topics: ["Stacks & Queues", "Strings"],
    constraints: [
      "0 <= s.length <= 10^4",
      "s consists only of the characters ( ) [ ] { }",
    ],
    inputFormat: "Line 1: the string s (may be empty)",
    outputFormat: "true when balanced, otherwise false.",
    examples: [
      { input: "({[]})", output: "true", explanation: "Every bracket is closed in order." },
      { input: "([)]", output: "false", explanation: "The [ is closed by the wrong type." },
    ],
    starterCode: `import java.util.ArrayDeque;
import java.util.Deque;

class Solution {
    public boolean isValid(String s) {
        // Your solution here.
        return false;
    }
}
`,
    functionSignature: "public boolean isValid(String s)",
    visibleTestCases: [
      { id: "visible-1", input: "({[]})", expectedOutput: "true" },
      { id: "visible-2", input: "([)]", expectedOutput: "false" },
      { id: "visible-3", input: "", expectedOutput: "true" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:min-stack",
    slug: "min-stack",
    title: "Design a stack that reports its minimum",
    description:
      "Design a stack that supports push, pop, top and retrieving the minimum element in constant time. The API is fixed; you are expected to design the class rather than call a ready-made structure.",
    difficulty: "medium",
    topics: ["Stacks & Queues", "OOP"],
    constraints: [
      "Operations must each take O(1) time",
      "-10^9 <= values <= 10^9",
      "pop and top are only called on a non-empty stack",
    ],
    inputFormat:
      "Line 1: q (number of operations)\nThen q lines, each either 'push <v>' or 'pop'",
    outputFormat:
      "One line per 'pop' or 'getMin' operation: the value or current minimum.",
    examples: [
      {
        input: "5\npush 3\npush 1\npop\npush 2\npop",
        output: "3\n1",
        explanation: "Each pop emits the removed value: 3 then 1.",
      },
      {
        input: "3\npush 5\npush 7\npush 2",
        output: "",
        explanation: "No pops, so no output lines.",
      },
    ],
    starterCode: `import java.util.ArrayDeque;
import java.util.Deque;

class MinStack {
    private final Deque<Integer> values = new ArrayDeque<>();
    private final Deque<Integer> minimums = new ArrayDeque<>();

    public void push(int value) {
        // Your solution here.
    }

    public void pop() {
        // Your solution here.
    }

    public int top() {
        // Your solution here.
        return 0;
    }

    public int getMin() {
        // Your solution here.
        return 0;
    }
}
`,
    functionSignature: "public void push(int value), public void pop(), public int top(), public int getMin()",
    visibleTestCases: [
      { id: "visible-1", input: "5\npush 3\npush 1\npop\npush 2\npop", expectedOutput: "3\n1" },
      { id: "visible-2", input: "3\npush 5\npush 7\npush 2", expectedOutput: "" },
      { id: "visible-3", input: "4\npush 4\npush 4\npop\npop", expectedOutput: "4\n4" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:reverse-linked-list-recursive",
    slug: "reverse-linked-list-recursive",
    title: "Reverse a singly linked list (recursive)",
    description:
      "Given the head of a singly linked list, reverse the list in place and return the new head. Implement the reversal recursively rather than iteratively.",
    difficulty: "easy",
    topics: ["Linked Lists", "Recursion"],
    constraints: ["0 <= list.length <= 10^4"],
    inputFormat:
      "Line 1: n\nLine 2: n space-separated values in list order",
    outputFormat: "The values of the reversed list, space separated.",
    examples: [
      { input: "5\n1 2 3 4 5", output: "5 4 3 2 1", explanation: "The order is fully reversed." },
      { input: "0\n", output: "", explanation: "An empty list stays empty." },
    ],
    starterCode: `class ListNode {
    int val;
    ListNode next;

    ListNode(int val) {
        this.val = val;
    }
}

class Solution {
    public ListNode reverse(ListNode head) {
        // Your solution here.
        return head;
    }
}
`,
    functionSignature: "public ListNode reverse(ListNode head)",
    visibleTestCases: [
      { id: "visible-1", input: "5\n1 2 3 4 5", expectedOutput: "5 4 3 2 1" },
      { id: "visible-2", input: "0\n", expectedOutput: "" },
      { id: "visible-3", input: "2\n9 1", expectedOutput: "1 9" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:remove-nth-from-end",
    slug: "remove-nth-from-end",
    title: "Remove the n-th node from the end of a list",
    description:
      "Given the head of a linked list, remove the n-th node from the end of the list and return the head. One pass, no extra storage beyond a fixed number of pointers.",
    difficulty: "medium",
    topics: ["Linked Lists", "Collections", "Java Streams"],
    constraints: [
      "1 <= n <= list.length <= 10^4",
      "n is always valid",
    ],
    inputFormat:
      "Line 1: n\nLine 2: list length m, then m values in list order",
    outputFormat: "The remaining values, space separated.",
    examples: [
      { input: "2\n5\n1 2 3 4 5", output: "1 2 3 5", explanation: "The 2nd from the end is 4, which is removed." },
      { input: "1\n1\n7", output: "", explanation: "Removing the only node leaves an empty list." },
    ],
    starterCode: `class ListNode {
    int val;
    ListNode next;

    ListNode(int val) {
        this.val = val;
    }
}

class Solution {
    public ListNode removeNthFromEnd(ListNode head, int n) {
        // Your solution here.
        return head;
    }
}
`,
    functionSignature: "public ListNode removeNthFromEnd(ListNode head, int n)",
    visibleTestCases: [
      { id: "visible-1", input: "2\n5\n1 2 3 4 5", expectedOutput: "1 2 3 5" },
      { id: "visible-2", input: "1\n1\n7", expectedOutput: "" },
      { id: "visible-3", input: "3\n4\n1 2 3 4", expectedOutput: "1 2 4" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:top-k-frequent-words",
    slug: "top-k-frequent-words",
    title: "Top k frequent words",
    description:
      "Return the k most frequent words in the input. Order ties by ascending word, and return exactly k words whenever at least k distinct words exist.",
    difficulty: "medium",
    topics: ["Java Streams", "HashMap", "Sorting & Searching"],
    constraints: [
      "1 <= words.length <= 10^5",
      "1 <= k <= words.length",
      "words contain lowercase English letters only",
    ],
    inputFormat:
      "Line 1: k\nLine 2: w (number of words)\nLine 3: w space-separated words",
    outputFormat: "The k words, separated by a single space.",
    examples: [
      {
        input: "2\n5\na b a c b a",
        output: "a b",
        explanation: "a appears 3 times and b twice, so a then b.",
      },
      {
        input: "1\n3\nx y z",
        output: "x",
        explanation: "All counts are 1, so ascending word order picks x.",
      },
    ],
    starterCode: `import java.util.List;

class Solution {
    public List<String> topKFrequent(List<String> words, int k) {
        // Your solution here.
        return List.of();
    }
}
`,
    functionSignature: "public List<String> topKFrequent(List<String> words, int k)",
    visibleTestCases: [
      { id: "visible-1", input: "2\n5\na b a c b a", expectedOutput: "a b" },
      { id: "visible-2", input: "1\n3\nx y z", expectedOutput: "x" },
      { id: "visible-3", input: "3\n6\nb a c a b c a", expectedOutput: "a b c" },
    ],
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:climbing-stairs",
    slug: "climbing-stairs",
    title: "Ways to climb a staircase",
    description:
      "You can climb either 1 or 2 steps at a time. How many distinct sequences reach the top of a staircase of n steps?",
    difficulty: "easy",
    topics: ["Dynamic Programming", "Recursion"],
    constraints: ["1 <= n <= 45"],
    inputFormat: "Line 1: n",
    outputFormat: "A single integer: the number of distinct ways.",
    examples: [
      { input: "2", output: "2", explanation: "1+1 or 2." },
      { input: "3", output: "3", explanation: "1+1+1, 1+2, 2+1." },
    ],
    starterCode: `class Solution {
    public int climbStairs(int n) {
        // Your solution here.
        return 0;
    }
}
`,
    functionSignature: "public int climbStairs(int n)",
    visibleTestCases: [
      { id: "visible-1", input: "2", expectedOutput: "2" },
      { id: "visible-2", input: "3", expectedOutput: "3" },
      { id: "visible-3", input: "5", expectedOutput: "8" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:best-time-to-buy-and-sell-stock",
    slug: "best-time-to-buy-and-sell-stock",
    title: "Best time to buy and sell a stock",
    description:
      "Given an array where the i-th element is the price of a stock on day i, return the maximum profit achievable from a single buy followed by a single later sell. If no profitable trade exists, return 0.",
    difficulty: "easy",
    topics: ["Arrays", "Greedy"],
    constraints: ["1 <= prices.length <= 10^5", "0 <= prices[i] <= 10^4"],
    inputFormat: "Line 1: n\nLine 2: n space-separated prices",
    outputFormat:
      "A single integer: the maximum profit, or 0 when no trade is profitable.",
    examples: [
      {
        input: "6\n7 1 5 3 6 4",
        output: "5",
        explanation: "Buy on day 2 at price 1 and sell on day 5 at price 6.",
      },
      {
        input: "5\n7 6 4 3 1",
        output: "0",
        explanation: "Prices only fall, so the best move is to never trade.",
      },
    ],
    starterCode: `class Solution {
    public int maxProfit(int[] prices) {
        // Your solution here.
        return 0;
    }
}
`,
    functionSignature: "public int maxProfit(int[] prices)",
    visibleTestCases: [
      { id: "visible-1", input: "6\n7 1 5 3 6 4", expectedOutput: "5" },
      { id: "visible-2", input: "5\n7 6 4 3 1", expectedOutput: "0" },
      { id: "visible-3", input: "1\n5", expectedOutput: "0" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:contains-duplicate",
    slug: "contains-duplicate",
    title: "Detect a duplicate value in an array",
    description:
      "Given an integer array, return true when any value appears at least twice; return false when every element is distinct. A linear scan with a hash set is the expected interview answer.",
    difficulty: "easy",
    topics: ["Arrays", "HashMap"],
    constraints: ["1 <= nums.length <= 10^5", "-10^9 <= nums[i] <= 10^9"],
    inputFormat: "Line 1: n\nLine 2: n space-separated integers",
    outputFormat: "true when a duplicate exists, otherwise false.",
    examples: [
      {
        input: "4\n1 2 3 1",
        output: "true",
        explanation: "The value 1 appears twice.",
      },
      {
        input: "4\n1 2 3 4",
        output: "false",
        explanation: "All four values are distinct.",
      },
    ],
    starterCode: `class Solution {
    public boolean containsDuplicate(int[] nums) {
        // Your solution here.
        return false;
    }
}
`,
    functionSignature: "public boolean containsDuplicate(int[] nums)",
    visibleTestCases: [
      { id: "visible-1", input: "4\n1 2 3 1", expectedOutput: "true" },
      { id: "visible-2", input: "4\n1 2 3 4", expectedOutput: "false" },
      { id: "visible-3", input: "1\n42", expectedOutput: "false" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:valid-anagram",
    slug: "valid-anagram",
    title: "Check whether two strings are anagrams",
    description:
      "Given two strings s and t, return true when t is an anagram of s, meaning the letters of t can be rearranged to spell s exactly. Both strings use lowercase English letters only.",
    difficulty: "easy",
    topics: ["Strings", "HashMap"],
    constraints: [
      "0 <= s.length, t.length <= 5 * 10^4",
      "s and t contain lowercase English letters only",
    ],
    inputFormat: "Line 1: the string s\nLine 2: the string t",
    outputFormat: "true when t is an anagram of s, otherwise false.",
    examples: [
      {
        input: "anagram\nnagaram",
        output: "true",
        explanation:
          "Both strings contain a, n and g with identical multiplicities.",
      },
      {
        input: "rat\ncar",
        output: "false",
        explanation: "The letter sets differ: r, a, t versus c, a, r.",
      },
    ],
    starterCode: `class Solution {
    public boolean isAnagram(String s, String t) {
        // Your solution here.
        return false;
    }
}
`,
    functionSignature: "public boolean isAnagram(String s, String t)",
    visibleTestCases: [
      { id: "visible-1", input: "anagram\nnagaram", expectedOutput: "true" },
      { id: "visible-2", input: "rat\ncar", expectedOutput: "false" },
      { id: "visible-3", input: "aabb\nabab", expectedOutput: "true" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:roman-to-integer",
    slug: "roman-to-integer",
    title: "Convert a Roman numeral to an integer",
    description:
      "Given a Roman numeral, convert it to its integer value. The six subtractive pairs IV, IX, XL, XC, CD and CM must be handled; every other symbol is added.",
    difficulty: "easy",
    topics: ["Strings", "HashMap"],
    constraints: [
      "1 <= s.length <= 15",
      "s is a valid Roman numeral in the range 1 to 3999",
    ],
    inputFormat: "Line 1: the Roman numeral s",
    outputFormat: "A single integer: the value of the numeral.",
    examples: [
      {
        input: "MCMXCIV",
        output: "1994",
        explanation: "M = 1000, CM = 900, XC = 90 and IV = 4.",
      },
      {
        input: "LVIII",
        output: "58",
        explanation: "L = 50, V = 5 and III = 3.",
      },
    ],
    starterCode: `class Solution {
    public int romanToInt(String s) {
        // Your solution here.
        return 0;
    }
}
`,
    functionSignature: "public int romanToInt(String s)",
    visibleTestCases: [
      { id: "visible-1", input: "MCMXCIV", expectedOutput: "1994" },
      { id: "visible-2", input: "LVIII", expectedOutput: "58" },
      { id: "visible-3", input: "III", expectedOutput: "3" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:longest-common-prefix",
    slug: "longest-common-prefix",
    title: "Longest common prefix of a word list",
    description:
      "Given an array of strings, return the longest prefix shared by every string. When the strings share nothing, return the empty string.",
    difficulty: "easy",
    topics: ["Strings", "Sorting & Searching"],
    constraints: [
      "1 <= strs.length <= 200",
      "0 <= strs[i].length <= 200",
      "strs[i] contains lowercase English letters only",
    ],
    inputFormat: "Line 1: k (number of strings)\nThen k lines, one string per line",
    outputFormat: "The longest common prefix, possibly an empty line.",
    examples: [
      {
        input: "3\nflower\nflow\nflight",
        output: "flow",
        explanation: "All three strings begin with flow.",
      },
      {
        input: "3\ndog\nracecar\ncar",
        output: "",
        explanation: "The first characters already differ, so the prefix is empty.",
      },
    ],
    starterCode: `class Solution {
    public String longestCommonPrefix(String[] strs) {
        // Your solution here.
        return "";
    }
}
`,
    functionSignature: "public String longestCommonPrefix(String[] strs)",
    visibleTestCases: [
      { id: "visible-1", input: "3\nflower\nflow\nflight", expectedOutput: "flow" },
      { id: "visible-2", input: "3\ndog\nracecar\ncar", expectedOutput: "" },
      { id: "visible-3", input: "2\ninterspecies\ninterstellar", expectedOutput: "inters" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:majority-element",
    slug: "majority-element",
    title: "Find the majority element",
    description:
      "Given an integer array, return the element that appears strictly more than half the time. Such an element is guaranteed to exist, so the answer is always unique.",
    difficulty: "easy",
    topics: ["Arrays", "HashMap"],
    constraints: [
      "1 <= nums.length <= 5 * 10^4",
      "-10^9 <= nums[i] <= 10^9",
      "A majority element always exists",
    ],
    inputFormat: "Line 1: n\nLine 2: n space-separated integers",
    outputFormat: "A single integer: the majority element.",
    examples: [
      {
        input: "3\n3 2 3",
        output: "3",
        explanation: "3 appears twice out of 3 elements.",
      },
      {
        input: "7\n2 2 1 1 1 2 2",
        output: "2",
        explanation: "2 appears four times out of 7 elements.",
      },
    ],
    starterCode: `class Solution {
    public int majorityElement(int[] nums) {
        // Your solution here.
        return 0;
    }
}
`,
    functionSignature: "public int majorityElement(int[] nums)",
    visibleTestCases: [
      { id: "visible-1", input: "3\n3 2 3", expectedOutput: "3" },
      { id: "visible-2", input: "7\n2 2 1 1 1 2 2", expectedOutput: "2" },
      { id: "visible-3", input: "1\n8", expectedOutput: "8" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:move-zeroes",
    slug: "move-zeroes",
    title: "Move all zeroes to the end",
    description:
      "Given an integer array, move every 0 to the end of the array while keeping the relative order of the non-zero elements. The result must be returned as a new array; a stable in-place partition is the interview follow-up.",
    difficulty: "easy",
    topics: ["Arrays"],
    constraints: ["1 <= nums.length <= 10^4", "-10^9 <= nums[i] <= 10^9"],
    inputFormat: "Line 1: n\nLine 2: n space-separated integers",
    outputFormat:
      "n space-separated integers: the non-zero values in their original order followed by all zeroes.",
    examples: [
      {
        input: "5\n0 1 0 3 12",
        output: "1 3 12 0 0",
        explanation:
          "The non-zero values keep their order; the two zeroes move to the end.",
      },
      {
        input: "3\n4 0 5",
        output: "4 5 0",
        explanation: "A single zero shifts right by one position.",
      },
    ],
    starterCode: `class Solution {
    public int[] moveZeroes(int[] nums) {
        // Your solution here.
        return nums;
    }
}
`,
    functionSignature: "public int[] moveZeroes(int[] nums)",
    visibleTestCases: [
      { id: "visible-1", input: "5\n0 1 0 3 12", expectedOutput: "1 3 12 0 0" },
      { id: "visible-2", input: "3\n4 0 5", expectedOutput: "4 5 0" },
      { id: "visible-3", input: "4\n0 0 0 0", expectedOutput: "0 0 0 0" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:house-robber",
    slug: "house-robber",
    title: "Maximum loot without robbing adjacent houses",
    description:
      "A row of houses each holds some loot. You cannot rob two adjacent houses. Return the maximum amount you can rob without triggering the alarm.",
    difficulty: "medium",
    topics: ["Dynamic Programming"],
    constraints: ["1 <= nums.length <= 100", "0 <= nums[i] <= 400"],
    inputFormat: "Line 1: n\nLine 2: n space-separated loot amounts",
    outputFormat: "A single integer: the maximum loot.",
    examples: [
      {
        input: "5\n2 7 9 3 1",
        output: "12",
        explanation: "Rob houses 1, 3 and 5: 2 + 9 + 1 = 12.",
      },
      {
        input: "4\n1 2 3 1",
        output: "4",
        explanation: "Rob houses 1 and 3: 1 + 3 = 4.",
      },
    ],
    starterCode: `class Solution {
    public int rob(int[] nums) {
        // Your solution here.
        return 0;
    }
}
`,
    functionSignature: "public int rob(int[] nums)",
    visibleTestCases: [
      { id: "visible-1", input: "5\n2 7 9 3 1", expectedOutput: "12" },
      { id: "visible-2", input: "4\n1 2 3 1", expectedOutput: "4" },
      { id: "visible-3", input: "1\n10", expectedOutput: "10" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:coin-change",
    slug: "coin-change",
    title: "Fewest coins to make an amount",
    description:
      "Given coin denominations and a target amount, return the fewest number of coins that sum to the amount. Each denomination may be used unlimited times. Return -1 when the amount cannot be formed, and 0 for amount 0.",
    difficulty: "medium",
    topics: ["Dynamic Programming", "Recursion"],
    constraints: [
      "1 <= coins.length <= 12",
      "1 <= coins[i] <= 2^31 - 1",
      "0 <= amount <= 10^4",
    ],
    inputFormat:
      "Line 1: c (number of denominations)\nLine 2: c space-separated coin values\nLine 3: the target amount",
    outputFormat:
      "A single integer: the fewest coins needed, or -1 when the amount is unreachable.",
    examples: [
      {
        input: "3\n1 2 5\n11",
        output: "3",
        explanation: "5 + 5 + 1 makes 11 with three coins.",
      },
      {
        input: "2\n2\n3",
        output: "-1",
        explanation: "An odd amount is impossible using only 2-valued coins.",
      },
    ],
    starterCode: `class Solution {
    public int coinChange(int[] coins, int amount) {
        // Your solution here.
        return -1;
    }
}
`,
    functionSignature: "public int coinChange(int[] coins, int amount)",
    visibleTestCases: [
      { id: "visible-1", input: "3\n1 2 5\n11", expectedOutput: "3" },
      { id: "visible-2", input: "2\n2\n3", expectedOutput: "-1" },
      { id: "visible-3", input: "1\n1\n0", expectedOutput: "0" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:unique-paths",
    slug: "unique-paths",
    title: "Count unique grid paths",
    description:
      "A robot starts at the top-left corner of an m by n grid and moves only right or down. Return the number of distinct paths that reach the bottom-right corner.",
    difficulty: "medium",
    topics: ["Dynamic Programming", "Recursion"],
    constraints: [
      "1 <= m, n <= 100",
      "The answer fits in a 32-bit integer",
    ],
    inputFormat: "Line 1: m\nLine 2: n",
    outputFormat: "A single integer: the number of unique paths.",
    examples: [
      {
        input: "3\n7",
        output: "28",
        explanation: "A 3 by 7 grid has 28 monotone lattice paths.",
      },
      {
        input: "3\n2",
        output: "3",
        explanation: "Down-down-right, down-right-down and right-down-down.",
      },
    ],
    starterCode: `class Solution {
    public int uniquePaths(int m, int n) {
        // Your solution here.
        return 0;
    }
}
`,
    functionSignature: "public int uniquePaths(int m, int n)",
    visibleTestCases: [
      { id: "visible-1", input: "3\n7", expectedOutput: "28" },
      { id: "visible-2", input: "3\n2", expectedOutput: "3" },
      { id: "visible-3", input: "1\n1", expectedOutput: "1" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:kth-largest-element",
    slug: "kth-largest-element",
    title: "Find the k-th largest element",
    description:
      "Given an integer array and an integer k, return the k-th largest element in sorted order, counting duplicates. Note that this is the k-th largest, not the k-th distinct value.",
    difficulty: "medium",
    topics: ["Arrays", "Sorting & Searching", "Java Streams"],
    constraints: [
      "1 <= k <= nums.length <= 10^5",
      "-10^4 <= nums[i] <= 10^4",
    ],
    inputFormat:
      "Line 1: k\nLine 2: n (number of elements)\nLine 3: n space-separated integers",
    outputFormat: "A single integer: the k-th largest element.",
    examples: [
      {
        input: "2\n6\n3 2 1 5 6 4",
        output: "5",
        explanation:
          "Sorted descending the array is 6 5 4 3 2 1, so the 2nd largest is 5.",
      },
      {
        input: "4\n9\n3 2 3 1 2 4 5 5 6",
        output: "4",
        explanation:
          "Sorted descending the array is 6 5 5 4 3 3 2 2 1, so the 4th largest is 4.",
      },
    ],
    starterCode: `class Solution {
    public int findKthLargest(int[] nums, int k) {
        // Your solution here.
        return 0;
    }
}
`,
    functionSignature: "public int findKthLargest(int[] nums, int k)",
    visibleTestCases: [
      { id: "visible-1", input: "2\n6\n3 2 1 5 6 4", expectedOutput: "5" },
      { id: "visible-2", input: "4\n9\n3 2 3 1 2 4 5 5 6", expectedOutput: "4" },
      { id: "visible-3", input: "1\n1\n7", expectedOutput: "7" },
    ],
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    isPublished: true,
  },
  {
    id: "java:trapping-rain-water",
    slug: "trapping-rain-water",
    title: "Trapping rain water",
    description:
      "Given an elevation map whose bar widths are all 1, return the total units of water it can trap after raining. This is a classic hard interview question solvable with two pointers, prefix maxima or a monotonic stack.",
    difficulty: "hard",
    topics: ["Arrays", "Dynamic Programming", "Stacks & Queues"],
    constraints: [
      "1 <= height.length <= 2 * 10^4",
      "0 <= height[i] <= 10^5",
    ],
    inputFormat: "Line 1: n\nLine 2: n space-separated elevations",
    outputFormat: "A single integer: the total units of trapped water.",
    examples: [
      {
        input: "12\n0 1 0 2 1 0 1 3 2 1 2 1",
        output: "6",
        explanation: "The classic elevation profile traps 6 units.",
      },
      {
        input: "5\n3 0 2 0 4",
        output: "7",
        explanation: "3 + 1 + 3 units sit above the two valleys.",
      },
    ],
    starterCode: `class Solution {
    public int trap(int[] height) {
        // Your solution here.
        return 0;
    }
}
`,
    functionSignature: "public int trap(int[] height)",
    visibleTestCases: [
      { id: "visible-1", input: "12\n0 1 0 2 1 0 1 3 2 1 2 1", expectedOutput: "6" },
      { id: "visible-2", input: "5\n3 0 2 0 4", expectedOutput: "7" },
      { id: "visible-3", input: "4\n1 2 3 4", expectedOutput: "0" },
    ],
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    isPublished: true,
  },
];

export const JAVA_PROBLEM_COUNT = PUBLIC_JAVA_PROBLEMS.length;
