/**
 * Editorial metadata for the Core Java interview question bank.
 *
 * Slug overrides let us keep stable, shareable URLs for the most-linked
 * questions; everything else derives its slug from `slugify(question)`.
 *
 * Difficulty / priority / tags / related-id metadata for each question now
 * lives next to the question in its chunk file (see `coreJavaQuestions/*`).
 * This module re-exports the merged map and the lookup helpers used by the
 * pages and the index.
 */
import type { InterviewQuestion, InterviewTopic } from "@/data/coreJavaInterviewData";
import { coreJavaQuestionMetaMap } from "@/data/coreJavaQuestions";

export type Difficulty = "easy" | "medium" | "hard";
export type InterviewPriority = "low" | "medium" | "high" | "very-high";

export interface CoreJavaQuestionMeta {
  slug?: string;
  difficulty?: Difficulty;
  priority?: InterviewPriority;
  tags?: string[];
  relatedQuestionIds?: string[];
  estimatedReadMinutes?: number;
  javaVersions?: string[];
}

export interface CoreJavaQuestionEntry {
  question: InterviewQuestion;
  topic: InterviewTopic;
  index: number;
  slug: string;
  meta: CoreJavaQuestionMeta;
}

export const JAVA_QUESTION_BASE_PATH = "/interview/java/core-java-qa";

/** Deterministic slug generator for question deep links. */
export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}

/**
 * Manual slug overrides keyed by question id.
 *
 * Keep this list short and only for questions that already have a stable,
 * shareable URL outside the site (bookmarks, blog posts). Most slugs are
 * generated by `slugify(question)`.
 */
export const CORE_JAVA_SLUG_OVERRIDES: Record<string, string> = {
  q003: "what-is-bytecode",
  q004: "jdk-jre-jvm-difference",
  q016: "string-immutability",
  q017: "string-pool",
  q019: "string-concatenation-in-loops",
  q021: "stringbuilder-vs-stringbuffer",
  q029: "equals-method-in-java",
  q030: "implementing-equals-method",
  q031: "hashcode-method-in-java",
  q032: "inheritance-with-examples",
  q046: "abstract-class-vs-interface",
  q055: "polymorphism-in-java",
  q091: "why-exception-handling",
  q106: "try-with-resources",
  q127: "what-is-serialization",
  q162: "hashmap-in-java",
  q163: "hashmap-methods",
  q165: "navigablemap-implementation",
  q167: "synchronized-vs-concurrent-collections",
  q172: "collection-initial-capacity",
  q173: "load-factor",
  q197: "synchronization-of-threads",
  q200: "thread-join-method",
  q202: "deadlock-in-java",
  q211: "java-streams-example",
  q212: "intermediate-operations-in-streams",
  q213: "terminal-operations-in-streams",
  q215: "lambda-expressions",
  q225: "new-features-in-java-8",
};

/** Merged per-id metadata sourced from chunk files. */
export const CORE_JAVA_QUESTION_META: Record<string, CoreJavaQuestionMeta> =
  coreJavaQuestionMetaMap;

export function getCoreJavaQuestionMeta(id: string): CoreJavaQuestionMeta {
  return CORE_JAVA_QUESTION_META[id] ?? {};
}

export function getCoreJavaQuestionSlug(question: InterviewQuestion): string {
  const meta = CORE_JAVA_QUESTION_META[question.id];
  if (meta?.slug) return meta.slug;
  return CORE_JAVA_SLUG_OVERRIDES[question.id] ?? slugify(question.question);
}

export function getCoreJavaQuestionDetailPath(question: InterviewQuestion): string {
  return `${JAVA_QUESTION_BASE_PATH}/${getCoreJavaQuestionSlug(question)}`;
}